version: 1
builder:
  configs:
    - documentation_targets:
        - Cloud
        - CloudAWS
        - CloudCore
        - CloudCloudflare
        - CloudDigitalOcean
        - CloudFastly
        - CloudVercel
